title: Locations of all courts in the UK
description: Location data for all courts in UK

publisher_text: Ministry of Justice
publisher_url: gov.uk/justice

license_text: UK Open Government Licence (OGL)
license_url: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/

frequency: Static

certificate_embed: 
